version: '3.9'

services:
  backend:
    build: ./
    container_name: Django
    ports:
      - ${BACKEND_PORT}:8000
    volumes:
      - ${STATIC_DIR}:/app
    environment:
      - DEBUG=false
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - backend
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pg-admin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80


networks:
  net: