version: '3.9'

services:
  backend:
    build: ./
    container_name: Django
    restart: always
    ports:
      - ${BACKEND_PORT}:8000
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - backend


networks:
  net: