title:
  - 'database developer'
  - 'sql developer'
  - 'database'
  - 'data engineer'
  - 'data warehouse'
  - 'BI Developer'
  - 'Business Intelligence'
  - 'etl'
excluded_title:
  - 'SAP'
  - 'cognito'
  - 'hana'
  - 'Principal'
  - 'Lead'
  - 'ts/sci'
  - 'Director'
  - 'php'
  - 'big data'
  - 'fabric'
  - 'informatica'
  - '.NET'
  - 'marklogic'
  - 'alation'
  - 'clearance'
  - 'peoplesoft'
  - 'deltek'
excluded_companies:
  - 'Cybercoders'
  - 'Roberthalf'
  - 'Jobot'
  - 'Booz Allen'
  - 'Accenture'
  - 'Deloitte'
  - 'Leidos'
  - 'Publicis Sapient'
  - 'Amazon'
  - 'Teksystems'
  - 'Kforce'
