# Generated by Django 3.2 on 2024-10-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=255)),
                ('filter_type', models.CharField(choices=[('IGNOR_ALL', 'IGNOR_ALL'), ('IGNOR_FROM_TITLE', 'IGNOR_FROM_TITLE'), ('IGNOR_FROM_DESCRIPTION', 'IGNOR_FROM_TITLE')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('job_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=50)),
                ('job_url', models.URLField()),
                ('job_url_direct', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_source', models.CharField(blank=True, max_length=50, null=True)),
                ('interval', models.CharField(blank=True, max_length=20, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('job_level', models.CharField(blank=True, max_length=50, null=True)),
                ('job_function', models.CharField(blank=True, max_length=50, null=True)),
                ('company_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('listing_type', models.CharField(max_length=50)),
                ('emails', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('company_url', models.URLField(blank=True, null=True)),
                ('company_url_direct', models.URLField(blank=True, null=True)),
                ('company_addresses', models.TextField(blank=True, null=True)),
                ('company_num_employees', models.IntegerField(blank=True, null=True)),
                ('company_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('logo_photo_url', models.URLField(blank=True, null=True)),
                ('banner_photo_url', models.URLField(blank=True, null=True)),
                ('ceo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ceo_photo_url', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('date_posted', models.DecimalField(decimal_places=1, max_digits=20)),
                ('job_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobfilter')),
                ('job_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobsearch')),
            ],
        ),
    ]
