# Generated by Django 3.2 on 2024-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joblisting_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobfilter',
            name='filter_type',
            field=models.CharField(choices=[('IGNOR_ALL', 'IGNOR_ALL'), ('IGNOR_FROM_TITLE', 'IGNOR_FROM_TITLE'), ('IGNOR_FROM_DESCRIPTION', 'IGNOR_FROM_DESCRIPTION'), ('COMPANY_NAME', 'COMPANY_NAME')], max_length=255),
        ),
    ]
