# Generated by Django 3.2 on 2024-11-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20241102_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfilter',
            name='filter_type',
            field=models.CharField(choices=[('IGNOR_ALL', 'IGNOR_ALL'), ('IGNOR_FROM_TITLE', 'IGNOR_FROM_TITLE'), ('IGNOR_FROM_DESCRIPTION', 'IGNOR_FROM_DESCRIPTION'), ('COMPANY_NAME', 'COMPANY_NAME'), ('KEY_WORD_NOT_IN_TITLE', 'KEY_WORD_NOT_IN_TITLE')], max_length=255),
        ),
    ]
