# Generated by Django 3.2 on 2024-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobfilter_filter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company_industry',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company_num_employees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='interval',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_function',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_id',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_level',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='listing_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='primary_key',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='site',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
